Traceback (most recent call last):
  File "/Users/kaihuang1122/Documents/ML/Final/MLP GPT/given_err.py", line 22, in <module>
    next(reader)  # 跳過標題行
    ^^^^^^^^^^^^
OSError: [Errno 89] Operation canceled
