Traceback (most recent call last):
  File "/Users/kaihuang1122/Documents/ML/Final/MLP GPT/given_err.py", line 5, in <module>
    import numpy as np
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/numpy/__init__.py", line 157, in <module>
    from . import random
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/numpy/random/__init__.py", line 180, in <module>
    from . import _pickle
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/numpy/random/_pickle.py", line 1, in <module>
    from .mtrand import RandomState
  File "numpy/random/mtrand.pyx", line 1, in init numpy.random.mtrand
  File "bit_generator.pyx", line 40, in init numpy.random.bit_generator
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/secrets.py", line 19, in <module>
    from random import SystemRandom
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/random.py", line 787, in <module>
    class SystemRandom(Random):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/random.py", line 215, in __init_subclass__
    def __init_subclass__(cls, /, **kwargs):

KeyboardInterrupt
